### ISSUE TITLE
Problem: rebuild_elasticsearch_aip_index_from_files error

### ISSUE THREAD

**Issue by hakamine** [archivematica/Issues#595]
**Expected behaviour**
rebuild_elasticsearch_aip_index_from_files management commands should complete without errors

**Current behaviour**
Error:
<pre>
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/manage$
ent/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/managem
ent/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/managem
ent/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/managem
ent/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_f
iles.py", line 298, in handle
    delete_existing_data=options["delete"],
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/rebuild_elasticsearch_aip_index_from_f
iles.py", line 171, in processAIPThenDeleteMETSFile
    identifiers=[],  # TODO get these
TypeError: index_aip_and_files() got an unexpected keyword argument 'path'
</pre>

**Steps to reproduce**
Invoke the management command

**Your environment (version of Archivematica, OS version, etc)**
AM qa/1.x 55bf3b9

This problem seems to have been introduced in https://github.com/artefactual/archivematica/commit/1689498a8f7dfcf6931d169e536282c8a1e862bd index_aip_and_files() was refactored (parameter names changed) but forgot to fix one of the places it is invoked.

---
**For Artefactual use:**
Please make sure these steps are taken before moving this issue from Review to Verified in Waffle:

- All PRs related to this issue are properly linked 👍
- All PRs related to this issue have been merged 👍
- Test plan for this issue has been implemented and passed 👍
- Documentation regarding this issue has been written and it has been added to the release notes, if needed 👍

**Comment by sevein** [comment]
This is a regression introduced by one of our most recent commits in AM v1.9.1 right?
If so, @sromkey you probably want to add the 1.9.1 milestone to this issue.

**Comment by jraddaoui** [comment]
I've recently executed this command with success in qa/1.x and I think @mamedin did it in stable. Please @mamedin, could you verify this issue if that's the case?

**Comment by mamedin** [comment]
Tested running:

<pre>
sudo -u archivematica bash -c " \
    set -a -e -x
    source /etc/default/archivematica-dashboard || \
        source /etc/sysconfig/archivematica-dashboard \
            || (echo 'Environment file not found'; exit 1)
    cd /usr/share/archivematica/dashboard
    /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python \
        manage.py rebuild_elasticsearch_aip_index_from_files \
            /var/archivematica/sharedDirectory/www/AIPsStore --delete-all
";
</pre>

* Works for AM v1.9.0
* Fails for AM v1.9.1-rc.2
* Works for AM v1.9.1-rc.4 

So this issue is fixed in AM v1.9.1-rc.4

**Comment by sallain** [comment]
Added to release notes
